packages:
  - packages/*
blockExoticSubdeps: true

catalog:
  effection: ^4.0.3
disallowWorkspaceCycles: true
# don't use workspace: protocol as covector will handle versions
linkWorkspacePackages: deep
