export const employees = [{
  id: 'admin',
  firstName: 'admin',
  lastName: 'admin',
  email: 'admin@hp.com',
  password: 'password',
  displayName: 'Louvenia Ledner',
  title: 'Principal Brand Facilitator',
  co: 'Fiji',
  c: 'AD',
  st: 'MN',
  l: 'Lake Jodyshire',
},
{
  id: '18',
  firstName: 'Sydni',
  lastName: 'Brekke',
  email: 'sydni.brekke@hp.com',
  password: 's27WXVRxhNXy0GE',
  displayName: 'Sydni Brekke',
  title: 'Dynamic Integration Architect',
  co: 'South Georgia and the South Sandwich Islands',
  c: 'BZ',
  st: 'KY',
  l: 'West Theodore',
}];
