name: Lint

on: push

jobs:
  run-linters:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v2
      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linters
        run: pnpm run lint

      # note this is required for type checking
      # in part due to graphql codegen
      - name: Build All
        run: pnpm run prepack

      - name: Run tsc
        run: pnpm run tsc
