name: Test

on: push

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4

      - run: wget https://dl.filippo.io/mkcert/latest?for=linux/amd64 -O mkcert
      - run: export CWD=$(pwd)
      - run: chmod +x mkcert
      - run: cp mkcert /home/runner/.local/bin
      - run: mkdir -p $HOME/.simulacrum/certs
      - run: export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
      - run: mkcert -install && mkcert localhost
        working-directory: $HOME/.simulacrum/certs

      - name: Install Node.js dependencies
        run: npm ci

      - run: npm run build
      - run: npm test
