name: Test

on: push

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Install Node.js dependencies
        run: npm ci

      - run: npm run build
      - run: npm test
