name: Test

on: push

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4

      - run: wget https://dl.filippo.io/mkcert/v1.4.4?for=linux/amd64
      - run: mv mkcert-v1.4.4-linux-amd64 mkcert
      - run: export CWD=$(pwd)
      - run: chmod +x mkcert
      - run: cp mkcert /usr/local/bin/
      - run: mkdir -p ~/.simulacrum/certs
      - run: export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
      - run: mkcert -install && mkcert localhost
        working-directory: ~/.simulacrum/certs

      - name: Install Node.js dependencies
        run: npm ci

      - run: npm run build
      - run: npm test
