name: Test

on: push

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v2
      - name: Install TLS Certificate
        uses: ./.github/actions/install-cert

      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm run prepack
      - run: pnpm test
